#!/bin/bash
# To create an empty file 
echo "This is to separate average structure of each cluster from clusters.xtc file."

#for i in `seq -w 05.00 0.25 08.50`; do
#for i in `seq -w 09.00 0.25 15.00`; do
for i in  08.75; do

# To separate average structure for each cluster of TASS window.
if [ "$( echo "$i < 8.6" | bc -l )" -eq 1 ];
then 
   cd tassn-$i\disn_sep_1/03_cluster/
echo 0 |   gmx_mpi trjconv -f clusters.xtc -s average.gro -o cluster-TASS-$i-.gro -sep
else
#	echo "$i + hello"
   cd tassn-$i\disn_sep/03_cluster/
echo 0 |   gmx_mpi trjconv -f clusters.xtc -s average.gro -o cluster-TASS-$i-.gro -sep
fi

cd ../../
echo "cbl-avi-TASS-$i Done."

done
